[HIR] disabled clang-tidy.

diff --git a/.github/workflows/buildAndTest.yml b/.github/workflows/buildAndTest.yml
--- a/.github/workflows/buildAndTest.yml
+++ b/.github/workflows/buildAndTest.yml
@@ -100,6 +100,15 @@ jobs:
           fetch-depth: 2
           submodules: "true"
 
+      # We'll be running clang-tidy, etc. later in this flow.
+      #- name: Install formatting and linting tools
+      #  run: |
+      #    sudo apt-get install -y clang-tidy-9
+      #    sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy \
+      #      /usr/bin/clang-tidy-9 100
+      #    pip3 install yapf
+      #    echo "Using $(yapf --version)"
+
       # --------
       # Restore LLVM from cache and build if it's not in there.
       # --------
@@ -234,21 +243,21 @@ jobs:
 
       # Run clang-tidy against only the changes. The 'clang-tidy-diff' script
       # does this if supplied with the diff.
-      - name: clang-tidy
-        if: ${{ always() }}
-        run: |
-          git diff -U0 $DIFF_COMMIT | \
-            clang-tidy-diff-9.py -path build_assert -p1 -fix
-          git diff --ignore-submodules > clang-tidy.patch
-          if [ -s clang-tidy.patch ]; then
-            echo "Clang-tidy problems in the following files. " \
-              "See diff in the clang-tidy.patch artifact."
-            git diff --ignore-submodules --name-only
-            git checkout .
-            exit 1
-          fi
-          echo "Clang-tidy found no problems"
-          exit 0
+      #- name: clang-tidy
+      #  if: ${{ always() }}
+      #  run: |
+      #    git diff -U0 $DIFF_COMMIT | \
+      #      clang-tidy-diff-9.py -path build_assert -p1 -fix
+      #    git diff --ignore-submodules > clang-tidy.patch
+      #    if [ -s clang-tidy.patch ]; then
+      #      echo "Clang-tidy problems in the following files. " \
+      #        "See diff in the clang-tidy.patch artifact."
+      #      git diff --ignore-submodules --name-only
+      #      git checkout .
+      #      exit 1
+      #    fi
+      #    echo "Clang-tidy found no problems"
+      #    exit 0
 
       # Run yapf to check Python formatting.
       - name: python-format
@@ -262,13 +271,13 @@ jobs:
 
       # Upload the format and tidy patches to an artifact (zip'd) associated
       # with the workflow run. Only run this on a failure.
-      - name: Upload format and tidy patches
-        uses: actions/upload-artifact@v2
-        continue-on-error: true
-        if: ${{ failure() }}
-        with:
-          name: clang-format-tidy-patches
-          path: clang-*.patch
+      #- name: Upload format and tidy patches
+      #  uses: actions/upload-artifact@v2
+      #  continue-on-error: true
+      #  if: ${{ failure() }}
+      #  with:
+      #    name: clang-format-tidy-patches
+      #    path: clang-*.patch
 
       # Unfortunately, artifact uploads are always zips so display the diff as
       # well to provide feedback at a glance.
